add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$status$git_branch$git_status"""

[character]
success_symbol = "[❯](#ed7eae)[❯](#92e8bf)[❯](#c088fc)"
error_symbol = "[❯](#ed7eae)[❯](#92e8bf)[❯](#c088fc)"
vicmd_symbol = "[❮](#c088fc)[❮](#92e8bf)[❮](#ed7eae)"

[git_branch]
format = '[$branch]($style) '
style = 'bold green'

[git_status]
format = '$all_status$ahead_behind '
ahead = '[⬆](bold purple) '
behind = '[⬇](bold purple) '
staged = '[✚](green) '
deleted = '[✖](pink) '
renamed = '[➜](purple) '
stashed = '[✭](cyan) '
untracked = '[◼](#e6fff2) '
modified = '[✱](blue) '
conflicted = '[═](yellow) '
diverged = '⇕ '
up_to_date = ''

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[docker_context]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
